#!/bin/bash
systemctl stop backyard-surv
systemctl disable backyard-surv
#if [[ -f $COMPOSER ]]; then
        #docker-compose -f /usr/local/bin/backyard/surv/docker-compose.yml down
#fi
rm -rf /usr/local/bin/backyard/surv 
exit 0
