#!/bin/bash
systemctl stop bird-watcher
systemctl disable bird-watcher
#if [[ -f $COMPOSER ]]; then
        #docker-compose -f /usr/local/bin/bird-watcher/docker-compose.yml down
#fi
rm -rf /usr/local/bin/bird-watcher/
exit 0
