version: '3.1'

services:
  nginx:
    image: birding-front:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: birding-front
    network_mode: host
    ports:
      - 8888:8888
    privileged: false
    restart: always
    volumes:
      - /opt/vc/lib/:/root/.vc/lib
    
