version: '3.1'

services:
  nginx:
    image: my-nginx:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nginx
    network_mode: host
    ports:
      - 80:80
    privileged: false
    restart: always
    volumes:
      - /opt/vc/lib/:/root/.vc/lib
    
